### PR TITLE
New web

### PR DESCRIPTION
**Pull request by rejdi**
#61 New web based on react.

### CODE REVIEW

**Review by lukipuki — CHANGES_REQUESTED** [review]
Please do a rebase/merge with master first.

**Comment by rejdi** [comment]
@lukipuki I already did.

**Comment by lukipuki** [comment]
Okay, I'm used to looking at individual commits and saw 0fb7132d51abf74110aa95f6a8417357d20eae1d which has been already merged. Also the commit 9ab7346aa45b081f5b981e79832c0fdf589214d1 is included, which has the old long Nginx settings.

It would be nicer if these would be removed or "squashed away". Makes the job of the reviewers easier!

Anyway, this seems like a massive PR (that's why I wanted to view individual commits). I think it should be split, but I don't have good suggestions, as I probably won't review the Javascript parts anyway. Paging @michalburger1 .

**Comment by miskosz** [comment]
@rejdi Can you make a PR which creates an empty React app (that will get changed into what we need in later PRs)? That might help in identifying what is the important code. Or maybe setting up an empty node project and CI setup can be also separated out (I'm not sure since I don't understand details, maybe you can consider.)

**Pull request closed without merging**
