### PR TITLE
Python package management. Test covid_web in CI.

### LINKED ISSUE #90: Single python venv
Covid_graphs and covid_web packages has it's own python virtual envs, but web has graphs as dependency. We should consider making one shared virtualenv.

### PR DESCRIPTION
**Pull request by miskosz**
Created a `python` directory that contains two packages:
* `covid_graphs` (moved from `/covid_graphs`)
* `covid_web` (moved from `/web/covid_web`)

Testing scripts were moved from `/covid_graphs` to `/python` and made to work with both packages.

### CODE REVIEW

**Review by lukipuki — APPROVED** [review]

**Comment by miskosz** [comment]
It is just a draft for now, I need to update Readme and test that docker is not broken :)

**Comment by rejdi** [comment]
@miskosz english please ;)
Also do we plan to keep react web under python-web? I'd suggest adding it to it's own directory `/react-web`

**Comment by miskosz** [comment]
I kept `react-web` with `nginx` it the `web` directory as it was. Do you suggest to pull it out?

**Comment by rejdi** [comment]
No, I overlooked it. I thought that it was moved together with python-web.

**Comment by miskosz** [comment]
The `Readme`s are a bit inconsistent in the end (I put docker usage to the python `Readme`), but we can fix that later.

**Pull request merged**
